// Bengali translation glossary for Islamic names
export const bengaliGlossary: Record<string, string> = {
  // Divine attributes (Asma ul Husna)
  "Allah": "আল্লাহ",
  "Merciful": "দয়ালু",
  "Compassionate": "করুণাময়",
  "King": "রাজা",
  "Holy": "পবিত্র",
  "Peaceful": "শান্তিময়",
  "Guardian": "রক্ষক",
  "Mighty": "পরাক্রমশালী",
  "Compeller": "বিধায়ক",
  "Supremely Great": "মহান",
  "Creator": "স্রষ্টা",
  "Evolver": "উদ্ভাবক",
  "Fashioner": "আকৃতিদাতা",
  "Forgiving": "ক্ষমাশীল",
  "Subduer": "পরাজয়কারী",
  "Bestower": "দাতা",
  "Provider": "রিজিকদাতা",
  "Opener": "উন্মোচনকারী",
  "All-Knowing": "সর্বজ্ঞ",
  "Constrictor": "সংকোচনকারী",
  "Expander": "সম্প্রসারণকারী",
  "Abaser": "অবনতকারী",
  "Exalter": "উন্নতকারী",
  "Honourer": "সম্মানদাতা",
  "Humiliator": "অপমানকারী",
  "All-Hearing": "সর্বশ্রোতা",
  "All-Seeing": "সর্বদ্রষ্টা",
  "Judge": "বিচারক",
  "Just": "ন্যায়বিচারক",
  "Subtle": "সূক্ষ্মদর্শী",
  "All-Aware": "সর্বজ্ঞাতা",
  "Forbearing": "সহনশীল",
  "Magnificent": "মহিমান্বিত",
  "Oft-Forgiving": "ক্ষমাশীল",
  "Appreciative": "কৃতজ্ঞ",
  "Most High": "সর্বোচ্চ",
  "Most Great": "মহান",
  "Preserver": "রক্ষণাবেক্ষণকারী",
  "Nourisher": "পুষ্টি সরবরাহকারী",
  "Reckoner": "হিসাবকারী",
  "Majestic": "মহিমান্বিত",
  "Generous": "উদার",
  "Watchful": "তত্ত্বাবধায়ক",
  "Responsive": "প্রতিক্রিয়াশীল",
  "All-Encompassing": "সর্বব্যাপী",
  "Wise": "প্রজ্ঞাবান",
  "Loving": "প্রেমময়",
  "Glorious": "মহিমাময়",
  "Resurrector": "পুনরুত্থানকারী",
  "Witness": "সাক্ষী",
  "Truth": "সত্য",
  "Trustee": "কর্মবিধায়ক",
  "Strong": "শক্তিশালী",
  "Firm": "দৃঢ়",
  "Protecting Friend": "বন্ধু",
  "Praiseworthy": "প্রশংসিত",
  "Counter": "গণনাকারী",
  "Originator": "উৎপাদনকারী",
  "Restorer": "পুনরুদ্ধারকারী",
  "Giver of Life": "জীবনদাতা",
  "Dealer of Death": "মৃত্যুদাতা",
  "Ever Living": "চিরজীবী",
  "Self-Subsisting": "স্বয়ংসম্পূর্ণ",
  "Perceiver": "উপলব্ধিকারী",
  "Glorious One": "মহিমান্বিত",
  "Only One": "একক",
  "Unique": "অদ্বিতীয়",
  "Eternal": "চিরন্তন",
  "Able": "সক্ষম",
  "Powerful": "শক্তিমান",
  "Expediter": "ত্বরিতকারী",
  "Delayer": "বিলম্বকারী",
  "First": "প্রথম",
  "Last": "শেষ",
  "Manifest": "প্রকাশ্য",
  "Hidden": "গোপন",
  "Governor": "শাসক",
  "Most Exalted": "সর্বোচ্চ",
  "Source of Good": "কল্যাণের উৎস",
  "Turner of Hearts": "হৃদয় পরিবর্তনকারী",
  "Avenger": "প্রতিশোধ গ্রহণকারী",
  "Pardoner": "ক্ষমাকারী",
  "Kind": "দয়ালু",
  "Owner of Sovereignty": "সার্বভৌমত্বের মালিক",
  "Lord of Majesty and Honour": "মহিমা ও সম্মানের অধিকারী",
  "Equitable": "ন্যায়পরায়ণ",
  "Gatherer": "একত্রিতকারী",
  "Rich": "স্বয়ংসম্পূর্ণ",
  "Enricher": "সমৃদ্ধকারী",
  "Preventer": "প্রতিরোধকারী",
  "Distresser": "কষ্টদানকারী",
  "Benefactor": "উপকারী",
  "Light": "আলো",
  "Guide": "পথপ্রদর্শক",
  "Incomparable": "অতুলনীয়",
  "Everlasting": "চিরস্থায়ী",
  "Inheritor": "উত্তরাধিকারী",
  "Guide to Right Path": "সঠিক পথের দিশারী",
  "Patient": "ধৈর্যশীল",

  // Common terms
  "Servant": "বান্দা",
  "Slave": "দাস",
  "Worshipper": "উপাসক",
  "Beloved": "প্রিয়",
  "Friend": "বন্ধু",
  "Helper": "সাহায্যকারী",
  "Supporter": "সমর্থক",
  "Noble": "মর্যাদাবান",
  "Honored": "সম্মানিত",
  "Blessed": "আশীর্বাদপ্রাপ্ত",
  "Pure": "পবিত্র",
  "Clean": "পরিষ্কার",
  "Righteous": "ধার্মিক",
  "Pious": "মুত্তাকী",
  "Devout": "নিষ্ঠাবান",
  "Faithful": "বিশ্বস্ত",
  "Trustworthy": "আস্থাভাজন",
  "Truthful": "সত্যবাদী",
  "Sincere": "আন্তরিক",
  "Obedient": "অনুগত",
  "Submissive": "বিনীত",
  "Humble": "নম্র",
  "Gentle": "কোমল",
  "Soft": "নরম",
  "Beautiful": "সুন্দর",
  "Handsome": "সুদর্শন",
  "Pleasant": "মনোরম",
  "Delightful": "আনন্দদায়ক",
  "Joyful": "আনন্দিত",
  "Happy": "খুশি",
  "Content": "সন্তুষ্ট",
  "Calm": "শান্ত",
  "Tranquil": "স্থির",
  "Serene": "নির্মল",
  "Bright": "উজ্জ্বল",
  "Shining": "চকচকে",
  "Radiant": "দীপ্তিমান",
  "Brilliant": "তেজস্বী",
  "Intelligent": "বুদ্ধিমান",
  "Learned": "পণ্ডিত",
  "Scholar": "আলেম",
  "Teacher": "শিক্ষক",
  "Student": "ছাত্র",
  "Seeker": "অন্বেষণকারী",
  "Finder": "আবিষ্কারক",
  "Leader": "নেতা",
  "Commander": "সেনাপতি",
  "Ruler": "শাসক",
  "Prince": "রাজপুত্র",
  "Princess": "রাজকন্যা",
  "Queen": "রানী",
  "Flower": "ফুল",
  "Rose": "গোলাপ",
  "Jasmine": "জুঁই",
  "Lily": "শাপলা",
  "Star": "তারা",
  "Moon": "চাঁদ",
  "Sun": "সূর্য",
  "Dawn": "ভোর",
  "Morning": "সকাল",
  "Evening": "সন্ধ্যা",
  "Night": "রাত",
  "Day": "দিন",
  "Lion": "সিংহ",
  "Eagle": "ঈগল",
  "Falcon": "বাজপাখি",
  "Pearl": "মুক্তা",
  "Jewel": "রত্ন",
  "Diamond": "হীরা",
  "Gold": "সোনা",
  "Silver": "রুপা",
  "River": "নদী",
  "Ocean": "সমুদ্র",
  "Mountain": "পর্বত",
  "Garden": "বাগান",
  "Paradise": "জান্নাত",
  "Heaven": "স্বর্গ",
  "Blessing": "আশীর্বাদ",
  "Gift": "উপহার",
  "Favor": "অনুগ্রহ",
  "Grace": "করুণা",
  "Mercy": "রহমত",
  "Compassion": "দয়া",
  "Love": "ভালোবাসা",
  "Affection": "স্নেহ",
  "Kindness": "সদয়তা",
  "Goodness": "ভালো",
  "Excellence": "উৎকর্ষ",
  "Perfection": "পূর্ণতা",
  "Success": "সাফল্য",
  "Victory": "বিজয়",
  "Triumph": "জয়",
  "Honor": "সম্মান",
  "Glory": "গৌরব",
  "Fame": "খ্যাতি",
  "Reputation": "সুনাম",
  "Dignity": "মর্যাদা",
  "Respect": "শ্রদ্ধা",
  "Reverence": "সম্মান",
  "Veneration": "পূজা",

  // Prophetic names
  "Moses": "মুসা",
  "Jesus": "ঈসা", 
  "Abraham": "ইব্রাহীম",
  "Isaac": "ইসহাক",
  "Jacob": "ইয়াকুব",
  "Joseph": "ইউসুফ",
  "David": "দাউদ",
  "Solomon": "সুলাইমান",
  "Job": "আইয়ুব",
  "Jonah": "ইউনুস",
  "Elijah": "ইলিয়াস",
  "Elisha": "আল-ইয়াসা",
  "Aaron": "হারূন",
  "Noah": "নূহ",
  "Adam": "আদম",
  "Idris": "ইদ্রিস",
  "Lot": "লূত",
  "Ishmael": "ইসমাইল",
  "Zachariah": "জাকারিয়া",
  "John": "ইয়াহইয়া",
  "Muhammad": "মুহাম্মদ",

  // Common phrases
  "of the": "এর",
  "of": "এর",
  "the": "",
  "and": "এবং",
  "or": "অথবা",
  "with": "সাথে",
  "from": "থেকে",
  "to": "প্রতি",
  "for": "জন্য",
  "in": "মধ্যে",
  "on": "উপর",
  "at": "এ",
  "by": "দ্বারা",
  "is": "হয়",
  "are": "হয়",
  "has": "আছে",
  "have": "আছে",
  "will": "হবে",
  "shall": "হবে",
  "would": "হবে",
  "could": "পারে",
  "should": "উচিত",
  "may": "পারে",
  "might": "পারে",
  "can": "পারে",
  "must": "অবশ্যই",
  "one who": "যে",
  "he who": "যে",
  "she who": "যে",
  "that which": "যা",
  "which": "যা",
  "who": "যে",
  "what": "কি",
  "when": "কখন",
  "where": "কোথায়",
  "why": "কেন",
  "how": "কীভাবে"
};

// Special patterns for "Servant of" constructions
export const servantPatterns: Record<string, string> = {
  "Servant of Allah": "আল্লাহর বান্দা",
  "Servant of the Merciful": "পরম দয়ালুর বান্দা",
  "Servant of the Compassionate": "পরম করুণাময়ের বান্দা",
  "Servant of the King": "রাজার বান্দা",
  "Servant of the Holy": "পবিত্রতার বান্দা",
  "Servant of the Peaceful": "শান্তিময়ের বান্দা",
  "Servant of the Guardian": "রক্ষকের বান্দা",
  "Servant of the Mighty": "পরাক্রমশালীর বান্দা",
  "Servant of the Wise": "প্রজ্ঞাবানের বান্দা",
  "Servant of the Generous": "দয়ালুর বান্দা",
  "Servant of the Just": "ন্যায়বিচারকের বান্দা",
  "Servant of the Forgiving": "ক্ষমাশীলের বান্দা",
  "Servant of the Provider": "রিজিকদাতার বান্দা",
  "Servant of the Creator": "স্রষ্টার বান্দা",
  "Servant of the All-Knowing": "সর্বজ্ঞের বান্দা",
  "Servant of the All-Seeing": "সর্বদ্রষ্টার বান্দা",
  "Servant of the All-Hearing": "সর্বশ্রোতার বান্দা",
  "Servant of the Most High": "সর্বোচ্চের বান্দা",
  "Servant of the Most Great": "মহানের বান্দা",
  "Servant of the Strong": "শক্তিশালীর বান্দা",
  "Servant of the Light": "আলোর বান্দা",
  "Servant of the Truth": "সত্যের বান্দা",
  "Servant of the Unique": "অদ্বিতীয়ের বান্দা",
  "Servant of the Eternal": "চিরন্তনের বান্দা",
  "Servant of the Living": "চিরজীবীর বান্দা",
  "Servant of the Self-Subsisting": "স্বয়ংসম্পূর্ণের বান্দা",
  "Servant of the Praiseworthy": "প্রশংসিতের বান্দা",
  "Servant of the Glorious": "মহিমাময়ের বান্দা",
  "Servant of the Patient": "ধৈর্যশীলের বান্দা"
};